language: node_js
branches:
  only:
  - dev
node_js:
  - "14.13.1"
cache: yarn
install:
  - yarn install

before_deploy:
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: dev
  local_dir: public
  target_branch: master
  email: szh@travis-ci.org
  name: 'suzh'
